# Does incremental backup of a folder to USB drive
# It uses robocopy command to do the main work.
# Usage: script-name Source-Folder-Name
# Output folder name is generated by concatenating script defined USBDrive and Prefix variables
# The script also strips trailing backslash from Source-Folder-Name if present before generating 
# output folder name. Note that Powershell adds trailing backslash by default to folder names when
# tab is used to step through files and folders being specified in a command on console.
#
param ($InputFolder="")
$OutputUSBDrive= "E:\"
$OutputFolderPrefix ="Back-"
function Usage {
  param ($cmdName)
  Write-Host Usage: $cmdName Source-Folder-Name
}

if ( "" -eq $InputFolder  ) {
    write-host "Input folder not specified."
    Usage $myInvocation.InvocationName
    exit 1
  }

$InputFolder = $InputFolder.trim()

$len = $InputFolder.length
if ("\" -eq $InputFolder.substring($len-1,1)) {
  $InputFolder = $InputFolder.substring(0, $len-1)
  Write-Host "Input parameter (folder name) had trailing backslash which was stripped" 
}

# Write-Host "Input parameter (folder name) is: '$InputFolder'" 
# Write-Host "Note that Powershell strips enclosing quote characters of parameters when passing them to script."

If ( -not (Test-Path -path $InputFolder -PathType Container)) {
  If (Test-Path -path $InputFolder) {
    Write-Host "Parameter specified: '$InputFolder' is not a directory. Aborting!"
  } Else {
    Write-Host "Parameter specified: '$InputFolder' does not exist. Aborting!"
  }
  Usage $myInvocation.InvocationName
  exit 1
}
$OutputUSBDrive= "E:\"
$OutputFolderPrefix ="Back-"

$OutputFolder = $OutputUSBDrive + $OutputFolderPrefix  + $InputFolder

Write-Host "Command (list only and not actual incremental backup) to be executed (for readability of below output, single quotes ..." 
Write-Host " are added around folder names but these added single quotes are not passed to robocopy command):", `n
Write-Host "robocopy '$InputFolder' '$OutputFolder' /E /XO /L", `n
$Choices = [System.Management.Automation.Host.ChoiceDescription[]] @("&yes", "&no")
$Choice = $host.UI.PromptForChoice("", "Proceed?", $Choices, 1)

if (1 -eq $Choice)
{
    Write-Host "Aborted!"
    exit 1
}

robocopy '$InputFolder' '$OutputFolder' /E /XO /L

Write-Host "Actual incremental backup command to be executed", `n
Write-Host "robocopy '$InputFolder' '$OutputFolder' /E /XO", `n
$Choices = [System.Management.Automation.Host.ChoiceDescription[]] @("&yes", "&no")
$Choice = $host.UI.PromptForChoice("", "Proceed with actual incremental backup command?", $Choices, 1)

if (1 -eq $Choice)
{
    Write-Host "Aborted!"
    exit 1
}

robocopy '$InputFolder' '$OutputFolder' /E /XO