# Copies contents of a folder/directory based on maxage but excludes some dirs like node_modules
# It uses CopyWoXF script to do the main work.
#
param ($InputFolder="", $MaxAge="1", $ExcludeFolders="")
$OutputFolder = ""
$OutputSuffix ="-maxage"
function Usage {
  param ($cmdName)
  Write-Host "Copy contents of a folder based on maxage excluding specified/default folders (e.g. node_modules and .next folders)"`n
  Write-Host Usage: $cmdName InputFolder [MaxAge ExcludeFolders]`n
  Write-Host If MaxAge is not specified, default value of 1 [day] is used
  Write-Host ExcludeFolders is passed as given to CopyWoXF.ps1
  Write-Host If ExcludeFolders is omitted`, default value of - is passed to CopyWoXF.ps1
  Write-Host "Output folder name is generated by concatenating today's date as yyyyMMdd- as prefix" `
    "and $OutputSuffix as suffix to Source-Folder-Name"
}

if ( "" -eq $InputFolder  ) {
    write-host "Input folder not specified."
    Usage $myInvocation.InvocationName
    exit 1
  }

$InputFolder = $InputFolder.trim()

$len = $InputFolder.length
if (($len -gt 1) -and (".\" -eq $InputFolder.substring(0,2))) {
    $InputFolder = $InputFolder.substring(2,$len-2)
    Write-Host "Input parameter (folder name) had starting dot and backslash which was stripped" 
}
$len = $InputFolder.length
if ("\" -eq $InputFolder.substring($len-1,1)) {
  $InputFolder = $InputFolder.substring(0, $len-1)
  Write-Host "Input parameter (folder name) had trailing backslash which was stripped" 
}

If ( -not (Test-Path -path $InputFolder -PathType Container)) {
  If (Test-Path -path $InputFolder) {
    Write-Host "Input folder parameter specified: '$InputFolder' is not a directory. Aborting!"
  } Else {
    Write-Host "Input folder parameter specified: '$InputFolder' does not exist. Aborting!"
  }
  Usage $myInvocation.InvocationName
  exit 1
}

$TodayDate = Get-Date -Format "yyyyMMdd-"
$OutputFolder = $TodayDate + $InputFolder + $OutputSuffix + "-" + $MaxAge
If (Test-Path -path $OutputFolder) {
  Write-Host "Output folder/directory name with auto prefix and suffix: '$OutputFolder' already exists. Aborting!"
  exit 1
} 

if ( "" -eq $ExcludeFolders  ) {
  $ExcludeFolders = "-"
}

$Cmd = "CopyWoXF $InputFolder $ExcludeFolders $MaxAge $OutputFolder"
Write-Host "Invoking $Cmd"
Invoke-Expression $Cmd